# Nome dell'applicazione
spring.application.name=MyFinBank

# Porta del server
server.port=8080
# Configurazione del database Oracle
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=fin_user
spring.datasource.password=fin_password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#Per utilizzzare DB reale nei test
spring.test.database.replace=NONE

# Dialettica JPA/hibernate per Oracle DB
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Profilo attivo
spring.profiles.active=test

# Configurazione Swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs

# Mostra i log solo per il pacchetto personalizzato
logging.level.com.myfinbank=INFO

# Disabilita i log per Hibernate
logging.level.org.hibernate=OFF

# Riduci i log di Spring
logging.level.org.springframework=WARN

# Disabilita completamente il livello root
logging.level.root=WARN


#Scadenza token
app.jwt.secret=7d8f0934e12f356c9b1d898fa692ea7b0490934faaa78d1a7649c4f0a497ec1f
app.jwt.accessTokenExpirationMs=600000
app.jwt.refreshTokenExpirationMs=1500000

server.error.include-message=always
server.error.include-binding-errors=always
# Disabilita il fancy HTML custom di Spring Boot
server.error.whitelabel.enabled=false

spring.messages.basename=messages
spring.messages.encoding=UTF-8


